### ISSUE TITLE
Better build script tooling

### ISSUE THREAD

**Issue by eritbh** [eritbh/new-reddit-comment-faces#10]
- [ ] Use something like `cross-env` to support setting environment variables within build scripts on Windows
- [ ] Use `rimraf` for clean script for Windows
- [ ] Add script for generating release builds (building chrome, renaming folder with version number, zipping, repeating for firefox)
- [ ] Create dedicated scripts for watch builds to avoid `-- --watch` messiness

**Comment by eritbh** [comment]
Actually, Firefox support dynamic `import()` in content scripts since 89 (https://bugzilla.mozilla.org/show_bug.cgi?id=1536094), so maybe I can get rid of the build process altogether now?

**Comment by eritbh** [comment]
> ...maybe a github action to automate releases?

Authored this for Toolbox, https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/.github/workflows/publish.yml - can adapt for here easily enough. note to self to get the CWS token in chromium
